# -*- coding: utf-8 -*-
"""Copy of Assignment2 ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19KqSGiKPwaCrdItX7RvolO70TMt_MP72
"""

# Assignment 
# r+ ,w+,a+

# the r means reading file; r+ means reading and writing the file.
# the w means writing file; w+ means reading and writing the file.
# the a means writing file,append mode; a+ means reading and writing file,append mode.

# in r+ mode ,we can read and write the file,but the file pointer position is at begining of the file.
# if we write the file directly,it will overwrite the begining content.

# a+ creates a new file or opens an existing file for reading and writing ,and the file pointer position at the end of the file.

file=open("c.txt","w+") 
file.write("test 1\n")
file.write("test 2\n")
file.write("test 3\n")
file.write("test 4\n")

file=open("c.txt","r+")
print(file.read())

file=open("c.txt","a+")
file.write(" hello welcome in python data science course")

file=open("c.txt","r+")
print(file.read())

